# Generated by Django 5.2.4 on 2025-07-06 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wixbuddy', '0003_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='dashboard_images/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
