# Generated by Django 5.2.4 on 2025-07-06 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wixbuddy', '0005_subscriptionplan_usersubscription_paymenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
