# Generated by Django 5.2.4 on 2025-07-07 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wixbuddy', '0008_resource_faq_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
    ]
