# Generated by Django 5.2.4 on 2025-07-08 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wixbuddy', '0009_remove_question_question_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=500)),
                ('options', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
