# Generated by Django 5.2.4 on 2025-07-08 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wixbuddy', '0010_questiontemplate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionTemplate',
        ),
    ]
