# Generated by Django 5.2.4 on 2025-07-08 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wixbuddy', '0012_alter_question_options_question_topic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='topic',
        ),
    ]
